export const cardWithHeaderSectionDate = [
  {
    id: 1,
    name: "Inventory",
    questionOne: "total number of medicine",
    answerOne: "200",
    questionTwo: "medicine group",
    answerTwo: "24",
    link: "#",
    linkLabel: "go to configuration",
  },
  {
    id: 2,
    name: "my pharmacy",
    questionOne: "total number of supplier",
    answerOne: "200",
    questionTwo: "total no of user",
    answerTwo: "05",
    link: "#",
    linkLabel: "go to user management",
  },
  {
    id: 3,
    name: "customer",
    questionOne: "total number of customer",
    answerOne: "200",
    questionTwo: "Frequently bought item",
    answerTwo: "ABC Drug",
    link: "#",
    linkLabel: "go to customer page",
  },
  {
    id: 4,
    name: "quick report",
    questionOne: "qty of medicine sold",
    answerOne: "200",
    questionTwo: "invoice generated",
    answerTwo: "50",
    link: "#",
    linkLabel: "go to report page",
  },
];
export const reportData = [
  {
    id: 4,
    name: "quick report",
    questionOne: "qty of medicine sold",
    answerOne: "200",
    questionTwo: "invoice generated",
    answerTwo: "50",
    link: "#",
  },
];
